### ISSUE TITLE
Episodes are marked as watched multiple times

### ISSUE THREAD

**Issue by Wahllow** [MediaBrowser/trakt#14]
Ever since version 3.3.6 this plugin has marked the same episode as watched at around the time the episode started and when it ends, both watched times are pushed to Trakt when the episode ends.

The workaround is to downgrade the plugin to version 3.3.5.

**Comment by LukePulverenti** [comment]
Closing due to age, but please feel free to reopen if you're still having an issue. I'm sure this has long been fixed. Thanks !
