### ISSUE TITLE
API Auth URL not working (404).

### ISSUE THREAD

**Issue by Evo-c** [MediaBrowser/trakt#2]
Hey there,

It seems the Trakt has changed or removed the auth method used in their api-v2.
This URL no longer works - https://api-v2launch.trakt.tv/auth/login

**Comment by Evo-c** [comment]
Just a quick update, I messaged someone from Trakt to see if anything had changed, here's what they got back to be with -

> That is an old authentication method that was removed about a year ago. You should move to using OAuth (http://docs.trakt.apiary.io/#reference/authentication-oauth/revoke-an-access_token) and also api.trakt.tv as the hostname.

**Comment by DK2Maverick** [comment]
Server started throwing plugin errors from the trakt plugin.

2017-11-29 21:04:28.738 Error HttpClient: Error ProtocolError getting response from https://api-v2launch.trakt.tv/sync/watched/movies
	*** Error Report ***
	Version: 3.2.40.0
	Command line: /usr/lib/emby-server/bin/MediaBrowser.Server.Mono.exe -programdata /var/lib/emby-server -restartpath /usr/lib/emby-server/restart.sh
	Operating system: Unix 4.4.0.101
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: False
	Mono: 5.4.1.6 (tarball Wed Nov  8 20:37:08 UTC 2017)
	Processor count: 12
	Program data path: /var/lib/emby-server
	Application directory: /usr/lib/emby-server/bin
	System.Net.WebException: The remote server returned an error: (401) Unauthorized.

Just confirming that https://api-v2launch.trakt.tv/auth/login is no longer working. Was working fine up to this morning. I changed the passwords just to be sure.  Trakt may have finally turned off the old authentication system the plugin was using?

**Comment by thiroxx** [comment]
i've compiled the fix. but there is still something wrong.
`2017-12-03 14:27:27.465 Info Trakt: No Users returned
2017-12-03 14:27:27.466 Info TaskManager: Import playstates from Trakt.tv Completed after 0 minute(s) and 0 seconds`
