### ISSUE TITLE
No Scheduled Task for Syncing to Trakt

### ISSUE THREAD

**Issue by sgtcoder** [MediaBrowser/trakt#21]
There is no option to sync playstates to Trakt, although that's what this plugins says it does.

Running Import Playstates from Trakt does not sync playstates to Trakt.

**Comment by LukePulverenti** [comment]
Hi, that's what the library sync does.

**Comment by sgtcoder** [comment]
Hi,

I had to regenerate a PIN, seems like I have to do that often.

I ran the Library sync and it still missed syncing some shows.

**Comment by LukePulverenti** [comment]
Hi, please try the latest update to the Trakt plugin that just went up. If there's still an issue after that, then please provide a specific example. Thanks.

**Comment by sgtcoder** [comment]
Thank you. I updated it and I will let you know if I see any issues.
