### ISSUE TITLE
Has the client id changed recently?

### ISSUE THREAD

**Issue by kaithar** [MediaBrowser/trakt#8]
I'm using the plugin from the catalog, it's trying to make this request for pin using this client id: 229219b2db18f433b5503358d7055e366e7ffb5f1dc1d6904d131d0ed806ccac

I'm getting this error:
Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.

Sooo, based on the url it's using, I'm assuming that the client id is wrong.  Has it changed recently?

**Comment by LukePulverenti** [comment]
We've pushed an update, thanks.
